name: Pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Haxe environment
        # You may pin to the exact commit or the version.
        # uses: krdlab/setup-haxe@3437f1adfca98b22815d926271cc39faaf996f25
        uses: krdlab/setup-haxe@v1.5.1
        # with:
          # Version Spec of the version to use. Example: 4.3.1
          # haxe-version: # default is 4.3.1
          # Used to specify the path to a dependency file.
          # cache-dependency-path: # optional
      - run: |
          haxe -version
          haxelib install ceramic
          sudo apt install unzip
          yes | haxelib run ceramic setup
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - run: ceramic clay build web --setup --assets
